# site settings
title: Jaehun You's Story
subtitle: by BECATRUE
email: jaehun0121@snu.ac.kr
description: This is my blog that comes whenever I'm bored.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Jaehun You
street_address: 1, Gwanak-ro
city: Gwanak-gu
state: Seoul
zip_code: 08826
country: Republic of Korea
phone: (+82) 10-3894-9521

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/becatrue
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
